name: peipoutine
description: Prince Edward Island Poutine Finder

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.12
  csv: ^5.0.1
  package_info_plus: ^1.4.3+1
  permission_handler: ^10.0.0
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.5
  geolocator: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
